[package]
name = "node-testing"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Test utilities for Substrate node."
edition = "2018"

[dependencies]
pallet-balances = { version = "2.0.0", git = "https://github.com/ProChain/substrate.git" }
sc-client = { version = "2.0.0", git = "https://github.com/ProChain/substrate.git" }
codec = { package = "parity-scale-codec", version = "1.0.0" }
pallet-contracts = { version = "2.0.0", git = "https://github.com/ProChain/substrate.git" }
pallet-grandpa = { version = "2.0.0", git = "https://github.com/ProChain/substrate.git" }
pallet-indices = { version = "2.0.0", git = "https://github.com/ProChain/substrate.git" }
sp-keyring = { version = "2.0.0", git = "https://github.com/ProChain/substrate.git" }
node-executor = { version = "2.0.0", path = "../executor" }
node-primitives = { version = "2.0.0", path = "../primitives" }
node-runtime = { version = "2.0.0", path = "../runtime" }
sp-core = { version = "2.0.0", git = "https://github.com/ProChain/substrate.git" }
sp-io = { version = "2.0.0", git = "https://github.com/ProChain/substrate.git" }
frame-support = { version = "2.0.0", git = "https://github.com/ProChain/substrate.git" }
pallet-session = { version = "2.0.0", git = "https://github.com/ProChain/substrate.git" }
sp-runtime = { version = "2.0.0", git = "https://github.com/ProChain/substrate.git" }
pallet-staking = { version = "2.0.0", git = "https://github.com/ProChain/substrate.git" }
sc-executor = { version = "2.0.0", git = "https://github.com/ProChain/substrate.git" }
frame-system = { version = "2.0.0", git = "https://github.com/ProChain/substrate.git" }
substrate-test-client = { version = "2.0.0", path = "../../../test-utils/client" }
pallet-timestamp = { version = "2.0.0", git = "https://github.com/ProChain/substrate.git" }
pallet-transaction-payment = { version = "2.0.0", git = "https://github.com/ProChain/substrate.git" }
pallet-treasury = { version = "2.0.0", git = "https://github.com/ProChain/substrate.git" }
wabt = "0.9.2"
hex-literal = "0.2.1"
