<template>
	<div class="loading">
		<div class="loadingio-spinner-bean-eater-hulfm8jq0s6">
			<div class="ldio-3qvneqds6ge">
				<div>
					<div></div>
					<div></div>
					<div></div>
				</div>
				<div>
					<div></div>
					<div></div>
					<div></div>
				</div>
			</div>
		</div>
	</div>
</template>
<script>
	export default {
		name: 'globalLoading'
	}
</script>
<style lang="scss" scoped>
	.loading {
		position: fixed;
		top: 0;
		left: 0;
		z-index: 121;
		width: 100%;
		height: 100%;
		background: rgba(0, 0, 0, 0.5);
		display: table-cell;
		vertical-align: middle;
		text-align: center;
	}
</style>
<style type="text/css">
	@keyframes ldio-3qvneqds6ge-1 {
		0% {
			transform: rotate(0deg)
		}

		50% {
			transform: rotate(-45deg)
		}

		100% {
			transform: rotate(0deg)
		}
	}

	@keyframes ldio-3qvneqds6ge-2 {
		0% {
			transform: rotate(180deg)
		}

		50% {
			transform: rotate(225deg)
		}

		100% {
			transform: rotate(180deg)
		}
	}

	.ldio-3qvneqds6ge>div:nth-child(2) {
		transform: translate(-15px, 0);
	}

	.ldio-3qvneqds6ge>div:nth-child(2) div {
		position: absolute;
		top: 20px;
		left: 20px;
		width: 60px;
		height: 30px;
		border-radius: 60px 60px 0 0;
		background: #f8b26a;
		animation: ldio-3qvneqds6ge-1 1s linear infinite;
		transform-origin: 30px 30px
	}

	.ldio-3qvneqds6ge>div:nth-child(2) div:nth-child(2) {
		animation: ldio-3qvneqds6ge-2 1s linear infinite
	}

	.ldio-3qvneqds6ge>div:nth-child(2) div:nth-child(3) {
		transform: rotate(-90deg);
		animation: none;
	}

	@keyframes ldio-3qvneqds6ge-3 {
		0% {
			transform: translate(95px, 0);
			opacity: 0
		}

		20% {
			opacity: 1
		}

		100% {
			transform: translate(35px, 0);
			opacity: 1
		}
	}

	.ldio-3qvneqds6ge>div:nth-child(1) {
		display: block;
	}

	.ldio-3qvneqds6ge>div:nth-child(1) div {
		position: absolute;
		top: 46px;
		left: -4px;
		width: 8px;
		height: 8px;
		border-radius: 50%;
		background: #e15b64;
		animation: ldio-3qvneqds6ge-3 1s linear infinite
	}

	.ldio-3qvneqds6ge>div:nth-child(1) div:nth-child(1) {
		animation-delay: -0.67s
	}

	.ldio-3qvneqds6ge>div:nth-child(1) div:nth-child(2) {
		animation-delay: -0.33s
	}

	.ldio-3qvneqds6ge>div:nth-child(1) div:nth-child(3) {
		animation-delay: 0s
	}

	.loadingio-spinner-bean-eater-hulfm8jq0s6 {
		width: 38px;
		height: 38px;
		overflow: hidden;
		background: rgba(255, 255, 255, 1);
		padding: 20px;
		border-radius: 5px;
		position: absolute;
		top: 50%;
		left: 50%;
		transform: translate(-50%, -50%);
	}

	.ldio-3qvneqds6ge {
		width: 100%;
		height: 100%;
		position: relative;
		transform: translateZ(0) scale(0.38);
		backface-visibility: hidden;
		transform-origin: 0 0;
		/* see note above */
	}

	.ldio-3qvneqds6ge div {
		box-sizing: content-box;
	}

	/* generated by https://loading.io/ */
</style>
