[package]
name = "node-runtime"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
build = "build.rs"

[dependencies]
# third-party dependencies
codec = { package = "parity-scale-codec", version = "1.0.6", default-features = false, features = ["derive"] }
integer-sqrt = { version = "0.1.2" }
safe-mix = { version = "1.0", default-features = false }
rustc-hex = { version = "2.0", optional = true }
serde = { version = "1.0.103", features = ["derive"], optional = true }
simple-json = { version = '0.1.2', git = "https://github.com/jingleizhang/simple-json.git", default-features = false }
hex = { version = "0.4.0", default-features = false }
num-bigint-dig = { version = "0.6.0", default-features = false}
num-traits = { version = "0.2.4", default-features = false}

# primitives
sp-authority-discovery = { version = "2.0.0", default-features = false, git = "https://github.com/ProChain/substrate.git" }
sp-consensus-babe = { version = "0.8", default-features = false, git = "https://github.com/ProChain/substrate.git" }
sp-block-builder = { git = "https://github.com/ProChain/substrate.git", default-features = false}
sp-inherents = { version = "2.0.0", default-features = false, git = "https://github.com/ProChain/substrate.git" }
node-primitives = { version = "2.0.0", path = "../primitives", default-features = false }
sp-offchain = { version = "2.0.0", default-features = false, git = "https://github.com/ProChain/substrate.git" }
sp-core = { version = "2.0.0", default-features = false, git = "https://github.com/ProChain/substrate.git" }
sp-std = { version = "2.0.0", default-features = false, git = "https://github.com/ProChain/substrate.git" }
sp-api = { version = "2.0.0", default-features = false, git = "https://github.com/ProChain/substrate.git" }
sp-runtime = { version = "2.0.0", default-features = false, git = "https://github.com/ProChain/substrate.git" }
sp-staking = { version = "2.0.0", default-features = false, git = "https://github.com/ProChain/substrate.git" }
sp-keyring = { version = "2.0.0", optional = true, git = "https://github.com/ProChain/substrate.git" }
sp-session = { version = "2.0.0", default-features = false, git = "https://github.com/ProChain/substrate.git" }
sp-transaction-pool = { version = "2.0.0", default-features = false, git = "https://github.com/ProChain/substrate.git" }
sp-version = { version = "2.0.0", default-features = false, git = "https://github.com/ProChain/substrate.git" }
sp-io = { version = "2.0.0", git = "https://github.com/ProChain/substrate.git", default-features = false }

# frame dependencies
pallet-authority-discovery = { version = "2.0.0", default-features = false, git = "https://github.com/ProChain/substrate.git" }
pallet-authorship = { version = "2.0.0", default-features = false, git = "https://github.com/ProChain/substrate.git" }
pallet-babe = { version = "2.0.0", default-features = false, git = "https://github.com/ProChain/substrate.git" }
pallet-balances = { version = "2.0.0", default-features = false, git = "https://github.com/ProChain/substrate.git" }
pallet-collective = { version = "2.0.0", default-features = false, git = "https://github.com/ProChain/substrate.git" }
pallet-contracts = { version = "2.0.0", default-features = false, git = "https://github.com/ProChain/substrate.git" }
pallet-contracts-rpc-runtime-api = { version = "2.0.0", default-features = false, git = "https://github.com/ProChain/substrate.git" }
pallet-democracy = { version = "2.0.0", default-features = false, git = "https://github.com/ProChain/substrate.git" }
pallet-elections-phragmen = { version = "2.0.0", default-features = false, git = "https://github.com/ProChain/substrate.git" }
frame-executive = { version = "2.0.0", default-features = false, git = "https://github.com/ProChain/substrate.git" }
pallet-finality-tracker = { version = "2.0.0", default-features = false, git = "https://github.com/ProChain/substrate.git" }
pallet-grandpa = { version = "2.0.0", default-features = false, git = "https://github.com/ProChain/substrate.git" }
pallet-im-online = { version = "2.0.0", default-features = false, git = "https://github.com/ProChain/substrate.git" }
pallet-indices = { version = "2.0.0", default-features = false, git = "https://github.com/ProChain/substrate.git" }
pallet-membership = { version = "2.0.0", default-features = false, git = "https://github.com/ProChain/substrate.git" }
pallet-nicks = { version = "2.0.0", default-features = false, git = "https://github.com/ProChain/substrate.git" }
pallet-offences = { version = "2.0.0", default-features = false, git = "https://github.com/ProChain/substrate.git" }
pallet-randomness-collective-flip = { version = "2.0.0", default-features = false, git = "https://github.com/ProChain/substrate.git" }
pallet-session = { version = "2.0.0", features = ["historical"], git = "https://github.com/ProChain/substrate.git", default-features = false }
pallet-staking = { version = "2.0.0", features = ["migrate"], git = "https://github.com/ProChain/substrate.git", default-features = false }
pallet-staking-reward-curve = { version = "2.0.0",  git = "https://github.com/ProChain/substrate.git" }
pallet-sudo = { version = "2.0.0", default-features = false, git = "https://github.com/ProChain/substrate.git" }
frame-support = { version = "2.0.0", default-features = false, git = "https://github.com/ProChain/substrate.git" }
frame-system = { version = "2.0.0", default-features = false, git = "https://github.com/ProChain/substrate.git" }
frame-system-rpc-runtime-api = { version = "2.0.0", default-features = false, git = "https://github.com/ProChain/substrate.git" }
pallet-timestamp = { version = "2.0.0", default-features = false, git = "https://github.com/ProChain/substrate.git" }
pallet-treasury = { version = "2.0.0", default-features = false, git = "https://github.com/ProChain/substrate.git" }
pallet-utility = { version = "2.0.0", default-features = false, git = "https://github.com/ProChain/substrate.git" }
pallet-transaction-payment = { version = "2.0.0", default-features = false, git = "https://github.com/ProChain/substrate.git" }
pallet-transaction-payment-rpc-runtime-api = { version = "2.0.0", default-features = false, git = "https://github.com/ProChain/substrate.git" }

# inner dependencies
did = { path = "../modules/did", default-features = false }
ads = { path = "../modules/ads", default-features = false }
prices = { path = "../modules/prices", default-features = false }
utilities = { path = "../modules/utilities", default-features = false }

[build-dependencies]
wasm-builder-runner = { version = "1.0.4", package = "substrate-wasm-builder-runner", path = "../../../utils/wasm-builder-runner" }

[dev-dependencies]
sp-io = { version = "2.0.0", git = "https://github.com/ProChain/substrate.git" }

[features]
default = ["std"]
std = [
	"sp-authority-discovery/std",
	"pallet-authority-discovery/std",
	"pallet-authorship/std",
	"sp-consensus-babe/std",
	"pallet-babe/std",
	"pallet-balances/std",
	"sp-block-builder/std",
	"codec/std",
	"pallet-collective/std",
	"pallet-contracts-rpc-runtime-api/std",
	"pallet-contracts/std",
	"pallet-democracy/std",
	"pallet-elections-phragmen/std",
	"frame-executive/std",
	"pallet-finality-tracker/std",
	"pallet-grandpa/std",
	"pallet-im-online/std",
	"pallet-indices/std",
	"sp-inherents/std",
	"pallet-membership/std",
	"pallet-nicks/std",
	"node-primitives/std",
	"sp-offchain/std",
	"pallet-offences/std",
	"sp-core/std",
	"pallet-randomness-collective-flip/std",
	"sp-std/std",
	"rustc-hex",
	"safe-mix/std",
	"serde/std",
	"pallet-session/std",
	"simple-json/std",
	"sp-api/std",
	"sp-runtime/std",
	"sp-staking/std",
	"pallet-staking/std",
	"sp-keyring",
	"sp-session/std",
	"pallet-sudo/std",
	"frame-support/std",
	"frame-system-rpc-runtime-api/std",
	"frame-system/std",
	"pallet-timestamp/std",
	"pallet-transaction-payment-rpc-runtime-api/std",
	"pallet-transaction-payment/std",
	"pallet-treasury/std",
	"sp-transaction-pool/std",
	"pallet-utility/std",
	"sp-version/std",
	"did/std",
	"ads/std",
	"prices/std",
	"utilities/std"
]
