[package]
name = "node-rpc"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
client = { package = "substrate-client", git = "https://github.com/ProChain/substrate.git" }
jsonrpc-core = "14.0.3"
node-primitives = { path = "../primitives" }
node-runtime = { path = "../runtime" }
sr-primitives = { git = "https://github.com/ProChain/substrate.git" }
pallet-contracts-rpc = { git = "https://github.com/ProChain/substrate.git" }
pallet-transaction-payment-rpc = { git = "https://github.com/ProChain/substrate.git" }
frame-system-rpc = { git = "https://github.com/ProChain/substrate.git" }
transaction_pool = { package = "substrate-transaction-pool", git = "https://github.com/ProChain/substrate.git" }
